# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='standard',
            field=models.ImageField(upload_to=posts.models.uploads_path),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='thumbnail',
            field=models.ImageField(upload_to=posts.models.uploads_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
