# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20161103_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='pets.Pet'),
        ),
    ]
