# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20161128_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likes', through='posts.UserLikesPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
