# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreceipt',
            name='receipt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
