# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20170511_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreceipt',
            old_name='developerPayload',
            new_name='developer_payload',
        ),
        migrations.RenameField(
            model_name='postreceipt',
            old_name='purchaseToken',
            new_name='purchase_token',
        ),
    ]
