# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeder',
            name='business_website',
        ),
        migrations.AddField(
            model_name='breeder',
            name='bussiness_website',
            field=models.URLField(null=True),
        ),
    ]
