# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeder',
            old_name='bussiness_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='breeder',
            old_name='bussiness_website',
            new_name='business_website',
        ),
    ]
