# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeder_type', models.CharField(max_length=100)),
                ('bussiness_name', models.CharField(max_length=100)),
                ('business_website', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Breeder',
                'verbose_name_plural': 'Breeders',
            },
        ),
    ]
