# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='area_interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'small_animal', b'Small Animal'), (b'large_animal', b'Large Animal'), (b'academia', b'Academia'), (b'industry', b'Industry'), (b'government', b'Government'), (b'zoo', b'Zoo'), (b'other', b'Other')], max_length=150),
        ),
    ]
