# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('id',), 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
