# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160920_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarianAreaInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='area_interest',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='area_interest',
            field=models.ManyToManyField(to='users.VeterinarianAreaInterest'),
        ),
    ]
