# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_breeder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_interest', models.CharField(max_length=150)),
                ('veterinary_school', models.CharField(max_length=50)),
                ('graduating_year', models.IntegerField()),
                ('veriy', models.BooleanField(default=False)),
                ('veterinarian_type', models.CharField(choices=[(b'tech', b'Technician'), (b'vet', b'Veterinarian'), (b'student', b'Student')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
            },
        ),
        migrations.AddField(
            model_name='breeder',
            name='veriy',
            field=models.BooleanField(default=False),
        ),
    ]
