# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160927_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.State'),
        ),
    ]
