# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160927_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeder',
            name='verified',
        ),
    ]
