# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160913_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeder',
            old_name='veriy',
            new_name='verified',
        ),
        migrations.RenameField(
            model_name='veterinarian',
            old_name='veriy',
            new_name='verified',
        ),
    ]
