# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_breeder_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='veterinarian_type',
            field=models.CharField(choices=[(b'3', b'Veterinarian'), (b'4', b'Student'), (b'5', b'Technician')], max_length=50),
        ),
    ]
