# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160929_1311'),
        ('users', '0003_auto_20160929_1857'),
    ]

    operations = [
    ]
