# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20160929_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_paid_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
