# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170121_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='area_interest',
            field=models.ManyToManyField(blank=True, to='users.AreaInterest'),
        ),
    ]
