# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170202_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='license_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='graduating_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='veterinary_school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
