# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 21:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(pets.models.get_limit_year), django.core.validators.MaxValueValidator(pets.models.get_current_year)]),
        ),
    ]
