# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20160929_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='birth_year',
        ),
    ]
