# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20160926_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
    ]
