# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='descritpion',
            new_name='description',
        ),
    ]
