# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptexts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptext',
            name='key',
            field=models.CharField(default='key', max_length=100),
            preserve_default=False,
        ),
    ]
